blank_issues_enabled: false
contact_links:
  - name: 🆘 Need help?
    url: https://github.com/Cyberclutch146/git-github-workshop/discussions
    about: Ask your question in the workshop chat or Discussions tab.
